{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "count": 90,
      "eventTime": null,
      "firstTimestamp": "2021-10-29T06:32:07Z",
      "involvedObject": {
        "apiVersion": "networking.k8s.io/v1beta1",
        "kind": "Ingress",
        "name": "ingress",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "82532251",
        "uid": "c6410c93-29fb-40bf-bba2-f1e50423f34e"
      },
      "kind": "Event",
      "lastTimestamp": "2021-11-01T08:42:06Z",
      "message": "Scheduled for sync",
      "metadata": {
        "creationTimestamp": "2021-10-29T06:32:07Z",
        "name": "ingress.16b26cb22939aa87",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "599753",
        "selfLink": "/api/v1/namespaces/7fd0ebe5431642bb9b3e7f0577/events/ingress.16b26cb22939aa87",
        "uid": "c6544fac-808e-47e9-8c6e-c0a1da591511"
      },
      "reason": "Sync",
      "reportingComponent": "",
      "reportingInstance": "",
      "source": {
        "component": "loadbalancer-controller"
      },
      "type": "Normal"
    },
    {
      "apiVersion": "v1",
      "count": 707,
      "eventTime": null,
      "firstTimestamp": "2021-10-30T13:24:23Z",
      "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "database-backup-1633824000-6jfpn",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "97337227",
        "uid": "28755586-fab2-43a4-91b8-03ccba76a3d6"
      },
      "kind": "Event",
      "lastTimestamp": "2021-11-01T08:41:32Z",
      "message": "Unable to attach or mount volumes: unmounted volumes=[shared-mount], unattached volumes=[default-token-qf5fv shared-mount]: timed out waiting for the condition",
      "metadata": {
        "creationTimestamp": "2021-10-31T01:44:55Z",
        "name": "database-backup-1633824000-6jfpn.16b2d1c628b35f7c",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "599743",
        "selfLink": "/api/v1/namespaces/7fd0ebe5431642bb9b3e7f0577/events/database-backup-1633824000-6jfpn.16b2d1c628b35f7c",
        "uid": "81597a75-9bcc-4c47-a3cf-a034322c1932"
      },
      "reason": "FailedMount",
      "reportingComponent": "",
      "reportingInstance": "",
      "source": {
        "component": "kubelet",
        "host": "gke-app-self--app-self--b2826dcb-o2l1"
      },
      "type": "Warning"
    },
    {
      "apiVersion": "v1",
      "count": 884,
      "eventTime": null,
      "firstTimestamp": "2021-10-30T13:45:03Z",
      "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "database-backup-1633824000-6jfpn",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "97337227",
        "uid": "28755586-fab2-43a4-91b8-03ccba76a3d6"
      },
      "kind": "Event",
      "lastTimestamp": "2021-11-01T08:34:29Z",
      "message": "(combined from similar events): MountVolume.SetUp failed for volume \"shared-pv-7fd0ebe5431642bb9b3e7f0577\" : mount failed: exit status 1\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/28755586-fab2-43a4-91b8-03ccba76a3d6/volumes/kubernetes.io~nfs/shared-pv-7fd0ebe5431642bb9b3e7f0577 --scope -- /home/kubernetes/containerized_mounter/mounter mount -t nfs 10.100.6.29:/ /var/lib/kubelet/pods/28755586-fab2-43a4-91b8-03ccba76a3d6/volumes/kubernetes.io~nfs/shared-pv-7fd0ebe5431642bb9b3e7f0577\nOutput: Running scope as unit: run-r219d468d2c644f8bad1a6d7631ae4668.scope\nMount failed: mount failed: exit status 32\nMounting command: chroot\nMounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs 10.100.6.29:/ /var/lib/kubelet/pods/28755586-fab2-43a4-91b8-03ccba76a3d6/volumes/kubernetes.io~nfs/shared-pv-7fd0ebe5431642bb9b3e7f0577]\nOutput: mount.nfs: Connection timed out\n",
      "metadata": {
        "creationTimestamp": "2021-11-01T01:04:29Z",
        "name": "database-backup-1633824000-6jfpn.16b2d2e6ee38fda5",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "599611",
        "selfLink": "/api/v1/namespaces/7fd0ebe5431642bb9b3e7f0577/events/database-backup-1633824000-6jfpn.16b2d2e6ee38fda5",
        "uid": "bae201f9-0d13-4995-81c3-7eec5e78af1a"
      },
      "reason": "FailedMount",
      "reportingComponent": "",
      "reportingInstance": "",
      "source": {
        "component": "kubelet",
        "host": "gke-app-self--app-self--b2826dcb-o2l1"
      },
      "type": "Warning"
    },
    {
      "apiVersion": "v1",
      "count": 168,
      "eventTime": null,
      "firstTimestamp": "2021-10-30T13:51:31Z",
      "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "database-backup-1633824000-6jfpn",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "97337227",
        "uid": "28755586-fab2-43a4-91b8-03ccba76a3d6"
      },
      "kind": "Event",
      "lastTimestamp": "2021-11-01T08:00:40Z",
      "message": "Unable to attach or mount volumes: unmounted volumes=[shared-mount], unattached volumes=[shared-mount default-token-qf5fv]: timed out waiting for the condition",
      "metadata": {
        "creationTimestamp": "2021-11-01T07:51:36Z",
        "name": "database-backup-1633824000-6jfpn.16b2d3413c4384ad",
        "namespace": "7fd0ebe5431642bb9b3e7f0577",
        "resourceVersion": "598390",
        "selfLink": "/api/v1/namespaces/7fd0ebe5431642bb9b3e7f0577/events/database-backup-1633824000-6jfpn.16b2d3413c4384ad",
        "uid": "f65b2c8d-2181-4613-984c-8a2c3d290f13"
      },
      "reason": "FailedMount",
      "reportingComponent": "",
      "reportingInstance": "",
      "source": {
        "component": "kubelet",
        "host": "gke-app-self--app-self--b2826dcb-o2l1"
      },
      "type": "Warning"
    }
  ],
  "kind": "List",
  "metadata": {
    "resourceVersion": "",
    "selfLink": ""
  }
}
